### PR TITLE
Allow root-relative URLs for non-stylesheet resources

### PR DESCRIPTION
**Pull request by davidtheclark**
I tried to address https://github.com/giakki/uncss/issues/287 by using jsdom's `resourceLoader` to amend root-relative URLs if the user has provided an `htmlroot`.

cc @vseventer @RyanZim

### CODE REVIEW

**Comment by vseventer** [comment]
I think we should add a test to make sure `resource.url.protocol === 'file://'`. Also, would this break relative URLs `<script src="test.js"></script>` when given a HTML root?

**Comment by RyanZim** [comment]
:+1: For adding the test.

@vseventer This change only affects URLs that start with `/`.

**Comment by davidtheclark** [comment]
Good thinking @vseventer: that test was broken. And it was not easy to fix ... ended up with a slightly hacky solution, so any improvement suggestions welcome. The problem is that within the `resourceLoader` function, all the pathnames are already absolute. Relative paths in the HTML have been converted into absolute paths. So somehow we have to distinguish between paths that *were* relative and were prefixed properly, and paths that were *root-relative* and were not prefixed properly.

It's weird to me that I haven't found an easier way to do this. Seems like every jsdom user should be running into the same problem, right?

**Comment by vseventer** [comment]
Thanks - I'll do some checks tonight. Would be curious to see if this works when a file is referenced by `../test.js`.

**Comment by RyanZim** [comment]
@davidtheclark ping?

**Comment by davidtheclark** [comment]
Thanks for the ping @RyanZim. Slipped through my radar. I'll look fix that problem within the next day or two.

**Comment by vseventer** [comment]
Had some time to play with this, and added a commit above. I made things work by assuming a relative script always lives within the `htmlroot` (think that is reasonable?). If not, assume it is a non-relative script and join it with the `htmlroot`.

**Comment by davidtheclark** [comment]
@vseventer That looks great! Sorry I've been too busy this week to look finish this up. Feel free to take it away.

**Comment by RyanZim** [comment]
@vseventer Is this merge-ready?

**Comment by vseventer** [comment]
Yeah, this should be good to go. Will run some final tests and merge.

**Comment by RyanZim** [comment]
Sorry so long; I finally got this patch released for testing as `uncss-jsdom` v2.0.0.

**Pull request merged**
